In [1]:
import numpy as np
array=np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np
arr=np.eye((3))
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
import numpy as np
random_number=np.random.randint(0,1,10)
print(random_number)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
import numpy as np
a=np.zeros((10))
print(a)
b=np.ones((10))

print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Q6).

In [13]:
import numpy as np
a=np.array([10,20,30,40,50])
b=a[2]
print(b)

30


Q7).

In [29]:
import numpy as np
a=np.arange(1,17).reshape(4,4)
print(a)
b=a[2:,3:]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[12]
 [16]]


Q8).

In [31]:
import numpy as np
a=np.array([5,10,15,20,25])
b=a[4]
print(b)

25


Q9).

In [52]:
import numpy as np
a=np.array([1,3,5,7,9,11])
print([a[1],a[3],a[4]])

[3, 7, 9]


Q

Q10)

In [51]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
b=a[1]
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1]]]


In [55]:
import numpy as np
a=np.array([2,4,6,8,10,12])
print(a[:4])


[2 4 6 8]


In [69]:
import numpy as np
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
print(a)
first_row=a[:,0]
print("first_row=",first_row)
second_row=a[:,1]
print("second_row=",second_row)
first_column=a[-1,:]
print("first_column=",first_column)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
first_row= [[1 2 3 4]]
second_row= [[5 6 7 8]]
first_column= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
